# AGENTS YAML (Updated)

wiki_researcher:
  role: "Wikipedia Research Specialist"
  goal: "Research and gather accurate information from Wikipedia articles, ensuring information is factually correct and short."
  backstory: "You are an expert researcher with years of experience extracting and organizing knowledge from Wikipedia. You have a keen eye for important details and can quickly identify the most relevant information on any topic. You only focus on main topics and always give output in small summarised manner"

content_simplifier:
  role: "Content Simplification Expert"
  goal: "Simplify complex concepts into easily digestible information while maintaining factual accuracy, adapting explanations for different professional domains and target audiences."
  backstory: "You specialize in making complicated subjects accessible to various age groups, education levels, and professional backgrounds (like engineers, business professionals, or medical experts). You know exactly how to break down complex ideas without losing their essence, tailoring the explanation to the listener's context."

comic_scriptwriter:
    role: "Comic Scriptwriter and Style Specialist"
    goal: "Transform simplified content into engaging, structured comic scripts in textual format, including suggesting appropriate characters based on the requested comic_style. Additionally, provide guidance on adapting the script's visual elements to match the style (manga, marvel, dc, indie), maintaining educational value."
    backstory: "You are a talented comic writer who knows how to create compelling visual narratives. You understand the balance between education and entertainment, and can structure information into detailed, structured textual formats ready for visual interpretation. With expertise in various comic traditions and artistic styles, you can conceptualize characters that fit specific genres (like manga, marvel, dc, indie), analyze script structures, and provide guidance or modifications to align them with the specific visual language and pacing of different comic art forms."

youtube_shorts_scriptwriter:
  role: "YouTube Shorts Scriptwriter"
  goal: "Create engaging and concise scripts for YouTube Shorts, providing text for narrators to speak in the background, ensuring the script aligns with the visuals and captures the audience's attention."
  backstory: "You are a creative scriptwriter specializing in crafting short, impactful scripts for YouTube Shorts. You excel at writing concise, engaging narration that complements visual content, ensuring the message is clear and captivating within the limited time frame of a short video."

quality_reviewer:
  role: "Factual Accuracy Corrector"
  goal: "Review the structured text comic script strictly for factual accuracy and correct any errors found directly within the text, meticulously preserving the original structure and formatting."
  backstory: "You have a sharp eye for detail and an unwavering commitment to factual correctness. You specialize in identifying and fixing inaccuracies in content while ensuring the original format and structure remain perfectly intact. Your job is to polish the script for accuracy before its final conversion."

javascript_coder:
  role: "Qualified JavaScript Expert"
  goal: "Convert comic scripts or other structured content (including style-specific elements like character suggestions) into proper JSON format, ensuring compliance with JSON standards and maintaining the integrity of the original content." # Goal updated slightly
  backstory: "You are a skilled JavaScript developer with extensive experience in working with JSON data structures. You excel at transforming complex scripts into well-structured JSON formats, ensuring accuracy, readability, and adherence to best practices. Your expertise ensures that the output is ready for seamless integration into various applications or platforms."

# TASKS YAML (Updated script_and_style_task and json_conversion_task)

research_task:
  description: >
    Research the Wikipedia article on "{{topic}}" and extract the most essential information
    for educational comic adaptation.

    REQUIREMENTS:
    - Maximum length: 300 words
    - Reading level: Appropriate for {{complexity_level}}
    - Must include:
      * Precise definition (1-2 sentences)
      * 3-5 key principles or components that define the topic
      * 1-2 real-world applications or examples
      * Historical context or development (1-2 sentences)

    EXCLUDE:
    - Tangential information
    - Excessive technical details
    - Controversial interpretations
    - Citations and references

  expected_output: >
    A concise, factual summary structured with clear headings:

    # CORE DEFINITION
    [1-2 sentence definition]

    # KEY COMPONENTS
    - [Component 1]
    - [Component 2]
    - [Component 3]

    # APPLICATIONS
    [1-2 concrete examples]

    # HISTORICAL CONTEXT
    [Brief historical development]

simplify_task:
  description: >
    Transform the research information into content optimized for the specified audience.
    # ... (Assume Target Audience, Requirements, Constraints are defined elsewhere or implicitly passed) ...
  expected_output: >
    A simplified version of the research text, ready for scripting:

    # SIMPLIFIED EXPLANATION
    [Main content adapted for target audience and domain]

    # KEY TAKEAWAYS
    - [Takeaway 1]
    - [Takeaway 2]
    - [Takeaway 3]

    # AUDIENCE-RELEVANT EXAMPLES
    [Examples tailored to target audience and domain]

script_and_style_task:
  description: >
    Create a structured educational comic script in a clear **textual format**, **suggesting character archetypes/names fitting the '{{comic_style}}'**, and provide guidance on adapting the script's visual elements to that style, considering these characteristics: {{style_characteristics}}.

    REQUIREMENTS:
    - Generate structured textual output using clear headings and delimiters.
    - **Suggest 2-3 potential character names or archetypes** suitable for the '{{comic_style}}' and the topic, placing them in a dedicated section.
    - Create approximately 4-6 chapters (adjust based on content flow).
    - Include sections for: Comic Topic, Total Chapters, Style Specific Character Suggestions, Style Adaptation Guidance, and for each chapter: Chapter Number, Chapter Title, Narration Box, Chat Bubbles (list of speaker/dialogue pairs, using suggested or appropriate character names), Conclusion, and a concise 2-3 line Image Context description.
    - Structure the narrative logically with an educational focus.
    - Maintain the original educational content and intent.
    - Ensure that the chapters have proper flow and cover all the educational content upon completion.
    - Provide brief guidance on visual style adaptation relevant to '{{comic_style}}'.

  expected_output: >
    A structured textual representation of the comic script including character suggestions and style guidance. Example format:

    ```text
    COMIC_TOPIC: {{topic}}
    TOTAL_CHAPTERS: 4
    COMIC_STYLE: {{comic_style}}

    STYLE_SPECIFIC_CHARACTER_SUGGESTIONS:
    - Archetype/Name 1 (e.g., Curious Student - 'Akira' if manga, 'Billy' if western)
    - Archetype/Name 2 (e.g., Knowledgeable Guide - 'Professor Kenji' if manga, 'Doc Sarah' if western)
    - Archetype/Name 3 (Optional - e.g., Skeptic Friend)

    STYLE_ADAPTATION_GUIDANCE:
    - [Brief point 1 about visual style adaptation for {{comic_style}}, e.g., Panel layout, line art, character expressions]
    - [Brief point 2...]

    --- CHAPTER 1 ---
    CHAPTER_NUMBER: 1
    CHAPTER_TITLE: Chapter 1: Introduction to...
    NARRATION_BOX: [Narrator sets the scene...]
    CHAT_BUBBLES:
    - CHARACTER: [Suggested Character Name 1, e.g., Akira]
      DIALOGUE: Wow, what is this?
    - CHARACTER: [Suggested Character Name 2, e.g., Professor Kenji]
      DIALOGUE: This explains the core concept...
    CONCLUSION: [Brief summary of chapter 1's key point]
    IMAGE_CONTEXT: [2-3 line description of the visual scene, mood, key elements for the panel, mentioning how {{comic_style}} might influence it.]

    --- CHAPTER 2 ---
    CHAPTER_NUMBER: 2
    CHAPTER_TITLE: ...
    NARRATION_BOX: ...
    CHAT_BUBBLES:
    - CHARACTER: [Character Name]
      DIALOGUE: ...
    CONCLUSION: ...
    IMAGE_CONTEXT: ...

    # ... more chapters ...
    ```

review_task:
  description: >
    Review the provided structured text comic script **strictly for factual errors** and **correct them directly within the text**. Ensure the original structure (headings, chapters, fields like NARRATION_BOX, CHAT_BUBBLES, CHARACTER_SUGGESTIONS, STYLE_GUIDANCE etc.) is perfectly maintained.

  REQUIREMENTS:
    - Input: Structured text script (output of script_and_style_task).
    - Identify any scientifically, historically, or generally factual inaccuracies in the content (narration, dialogue, conclusion, etc.).
    - Correct identified errors directly in the text.
    - Crucially preserve the exact textual structure and formatting** (e.g., --- CHAPTER X ---, NARRATION_BOX:, indentation in CHAT_BUBBLES, the character/style sections).
    - If no errors are found, return the original script unchanged.
    - Do NOT add comments, annotations, or reports. Only output the corrected (or original, if no errors) script text.

  expected_output: >
    The original structured text script, potentially with factual corrections applied directly to the content of fields like NARRATION_BOX, DIALOGUE, CONCLUSION, etc., while maintaining the identical overall structure including character and style sections.

    Example (if an error in Chapter 1 dialogue was corrected):
    ```text
    COMIC_TOPIC: {{topic}}
    TOTAL_CHAPTERS: 4
    COMIC_STYLE: {{comic_style}}

    STYLE_SPECIFIC_CHARACTER_SUGGESTIONS:
    - Archetype/Name 1 (e.g., Curious Student - 'Akira' if manga, 'Billy' if western)
    - Archetype/Name 2 (e.g., Knowledgeable Guide - 'Professor Kenji' if manga, 'Doc Sarah' if western)
    - Archetype/Name 3 (Optional - e.g., Skeptic Friend)

    STYLE_ADAPTATION_GUIDANCE:
    - [Brief point 1 about visual style adaptation for {{comic_style}}, e.g., Panel layout, line art, character expressions]
    - [Brief point 2...]


    --- CHAPTER 1 ---
    CHAPTER_NUMBER: 1
    CHAPTER_TITLE: Chapter 1: Introduction to...
    NARRATION_BOX: [Narrator sets the scene...]
    CHAT_BUBBLES:
    - CHARACTER: Akira
      DIALOGUE: Wow, what is this?
    - CHARACTER: Professor Kenji
      DIALOGUE: [Corrected factual explanation replacing the original dialogue...]
    CONCLUSION: [Brief summary of chapter 1's key point]
    IMAGE_CONTEXT: [2-3 line description of the visual scene, mood, and key elements for the panel]

    # ... rest of the script, potentially with other corrections or unchanged ...
    ```

json_conversion_task:
  description: >
    Convert the reviewed structured text comic script into a validated JSON format.

  REQUIREMENTS:
    - Input: Structured text script (following the format output by script_and_style_task and potentially modified by review_task).
    - Output: A single, valid JSON string.
    - Accurately map all elements (topic, chapters, titles, narration, chat bubbles, conclusion, image context, **comic style, character suggestions, and style guidance**) from the text structure to the specified JSON structure.
    - Ensure the output JSON strictly adheres to JSON syntax rules.
    - The JSON structure should match the defined format below.

  expected_output: >
    A validated JSON string representing the comic script. The JSON object should have keys like "comic_topic", "total_chapters", "comic_style", "style_specific_character_suggestions", "style_adaptation_guidance", and "chapters". The "chapters" key should hold a list of chapter objects.

    ```json
    {
      "comic_topic": "{{topic}}",
      "total_chapters": 4,
      "comic_style": "{{comic_style}}",
      "style_specific_character_suggestions": [
        "Archetype/Name 1 (e.g., Curious Student - 'Akira' if manga, 'Billy' if western)",
        "Archetype/Name 2 (e.g., Knowledgeable Guide - 'Professor Kenji' if manga, 'Doc Sarah' if western)",
        "Archetype/Name 3 (Optional - e.g., Skeptic Friend)"
      ],
      "style_adaptation_guidance": [
        "[Brief point 1 about visual style adaptation for {{comic_style}}, e.g., Panel layout, line art, character expressions]",
        "[Brief point 2...]"
      ],
      "chapters": [
        {
          "chapter_number": 1,
          "chapter_title": "Chapter 1: Introduction to...",
          "narration_box": "[Narrator sets the scene...]",
          "chat_bubbles": [
            {"character": "Akira", "dialogue": "Wow, what is this?"},
            {"character": "Professor Kenji", "dialogue": "This explains the core concept..."}
          ],
          "conclusion": "[Brief summary of chapter 1's key point]",
          "image_context": "[2-3 line description of the visual scene, mood, and key elements for the panel, mentioning how {{comic_style}} might influence it.]"
        },
        // ... more chapters mapped from text
      ]
    }
    ```

youtube_shorts_scriptwriter_task:
  description: >
    Generate a concise and engaging narration script suitable for a YouTube Short,
    based *specifically* on the provided comic script content below.

    The narration should:
    - Directly reflect the key points and flow presented in the comic script.
    - Align with the educational topic (e.g., Gravity).
    - Be captivating and easy to understand for a general YouTube Shorts audience.
    - Be formatted as a series of short sentences or phrases, suitable for voiceover timing.

    **Comic Script Content (JSON format):**
    ```json
    {{comic_script}}
    ```


    Focus *only* on creating the narration text based on the dialogue, narration boxes, and conclusions in the provided JSON. Do not add introductions or conclusions beyond the narration itself.

  expected_output: >
    A concise narration script for the YouTube Short, clearly marked with 'NARRATION_SCRIPT:'.
      Each line should represent a segment of the narration.

      Example Format:
      ```text
      NARRATION_SCRIPT:
      - Ever wonder how plants make their food? It's Photosynthesis!
      - Plants use sunlight, water, and carbon dioxide to create energy.
      - Sunlight acts like a spark, starting the process in their leaves.
      - The result? Oxygen for us and glucose for the plant!
      - Without photosynthesis, life on Earth wouldn't exist.
      - It's nature's way of turning light into life!
      ```